services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: Ulule-test
    ports:
      - "${APP_PORT}:8080"
    environment:
      DSN: "postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/ulule"
      APP_PORT: ":${APP_PORT}"
    depends_on:
      - db
    networks:
      - main

  db:
    build:
      context: ./script/db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: postgres.sh
      interval: "5s"
    ports:
      - ${DB_HOST}:${DB_PORT}
    networks:
      - main

networks:
  main: