services:
  app:
    build:
      context: ../.
      args:
        BUILD_ARGS: ""
        GO_MAIN: "/Ulule"
    container_name: Ulule-test
    restart: always
    environment:
      DSN: "postgres://${DB_USER}:${DB_PASSWORD}@127.0.0.1:${DB_PORT}/${DB_NAME}"
      APP_PORT: "${APP_PORT}"